// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerInfo } from "../McpServerInfo";
import type { Resource } from "../Resource";
import type { ResourceTemplate } from "../ResourceTemplate";
import type { Tool } from "../Tool";
import type { McpAuthStatus } from "./McpAuthStatus";

export type McpServerStatus = { name: string, serverInfo: McpServerInfo | null, tools: { [key in string]?: Tool }, resources: Array<Resource>, resourceTemplates: Array<ResourceTemplate>, authStatus: McpAuthStatus,
/**
 * Human-readable source of the winning server definition (e.g.
 * "config.toml (user)" or "plugin `acme`"). Null when unknown.
 */
source: string | null,
/**
 * Sources of same-name definitions that lost to the winning one.
 */
overriddenSources: Array<string>,
/**
 * Whether the connected server declared the experimental `codex/channel`
 * capability. Null while the server has not (yet) initialized.
 */
declaresChannelCapability: boolean | null, };
